#
# Automatically merges pull requests opened by keyman-server.
#
# This workflow will be triggered to merge the PR once approved by the
# auto-approve-keyman-server-pr.yml script.
#
name: Auto Merge PRs from keyman-server
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  status:
  check_suite:
    types:
      - completed
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
    - name: auto merge PR from keyman-server
      uses: "pascalgn/automerge-action@22948e0bc22f0aa673800da838595a3e7347e584" # v0.15.6
      if: github.actor == 'keyman-server'
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        MERGE_LABELS: "auto"
        MERGE_FORKS: false
        MERGE_RETRY: 6
        MERGE_RETRY_SLEEP: 30000
