# Trigger a deployment by pinging our webhook
name: Deploy app to Azure Web App with PHP

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Invoke deployment hook
      uses: distributhor/workflow-webhook@3b1dfb659938cacd1f6eab6e2c79478b5b1ac06f
      env:
        webhook_url: https://s-keyman-com.azurewebsites.net/api/deploy.php
        webhook_secret: ${{ secrets.S_KEYMAN_COM_DEPLOY_KEY }}
